{
  "comments": [
    {
      "key": {
        "uuid": "63a38452_ded13215",
        "filename": "vpd-manager/editor_impl.cpp",
        "patchSetId": 1
      },
      "lineNbr": 36,
      "author": {
        "id": 1000522
      },
      "writtenOn": "2021-04-07T07:30:14Z",
      "side": 1,
      "message": "If we are skipping update record because of ECC check fail, then should we log PEL? Should we throw vpdEccException in this case?",
      "revId": "02f8af63e6f66b1605c9fd22fcbcff9effbe4081",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "03158992_18c3bdcf",
        "filename": "vpd-manager/editor_impl.cpp",
        "patchSetId": 1
      },
      "lineNbr": 36,
      "author": {
        "id": 1000362
      },
      "writtenOn": "2021-04-07T07:39:04Z",
      "side": 1,
      "message": "we can throw vpdECCException..but we can\u0027t create PEL from this Write Keyword dbus-api call..\nas the PEL expects data from the caller to proceed further - and the caller writeKeyword dbus-api will wait for the PEL to complete its execution.. there comes a deadlock.. and a dbus call timeout error is thrown in console",
      "parentUuid": "63a38452_ded13215",
      "revId": "02f8af63e6f66b1605c9fd22fcbcff9effbe4081",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "1ce33e24_fda76185",
        "filename": "vpd-manager/editor_impl.cpp",
        "patchSetId": 1
      },
      "lineNbr": 36,
      "author": {
        "id": 1000522
      },
      "writtenOn": "2021-04-07T07:41:14Z",
      "side": 1,
      "message": "No, My query was just if we should throw vpdEccException from here. The exception will itself take care of PEL.\nI should have phrased it more clearly.",
      "parentUuid": "03158992_18c3bdcf",
      "revId": "02f8af63e6f66b1605c9fd22fcbcff9effbe4081",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}