{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "171026bd_624b1059",
        "filename": "vpd-manager/include/event_logger.hpp",
        "patchSetId": 13
      },
      "lineNbr": 221,
      "author": {
        "id": 1001932
      },
      "writtenOn": "2025-06-10T07:24:27Z",
      "side": 1,
      "message": "not throwing exception instead catching and logging in the API ?",
      "revId": "366c7fb32580e6d2cee36b2ff3d82e43ea96812b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "6a2c7362_69dfe368",
        "filename": "vpd-manager/src/event_logger.cpp",
        "patchSetId": 13
      },
      "lineNbr": 394,
      "author": {
        "id": 1001932
      },
      "writtenOn": "2025-06-10T07:24:27Z",
      "side": 1,
      "message": "not catching any other than SdBusError errors ?\nshould we catch all error and log.",
      "revId": "366c7fb32580e6d2cee36b2ff3d82e43ea96812b",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}