{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "e0b0cc0e_4a6fd9f8",
        "filename": "vpd-manager/include/utility/vpd_specific_utility.hpp",
        "patchSetId": 5
      },
      "lineNbr": 744,
      "author": {
        "id": 1000522
      },
      "writtenOn": "2025-02-25T11:36:16Z",
      "side": 1,
      "message": "Why \"Data Exception:\" is this as a default prefix?",
      "revId": "513cbe46b2cdf8f81bf770c7fb36b8d1dfc22217",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}